### ISSUE TITLE
Documentation Update - Include tidyclust tag on RStudio Community link on https://tidyclust.tidymodels.org/

### ISSUE THREAD

**Issue by EconomiCurtis** [tidymodels/tidyclust#110]
On https://tidyclust.tidymodels.org/ under contributing (https://tidyclust.tidymodels.org/index.html#contributing),
one bullet currently reads, 

> For questions and discussions about tidymodels packages, modeling, and machine learning, please [post on RStudio Community](https://community.rstudio.com/new-topic?category_id=15&tags=tidymodels,question).

Could I suggest updating that link to include the tidyclust tag? 
https://community.rstudio.com/new-topic?category_id=15&tags=tidymodels,question,tidyclust

And then note that you can follow the tag (https://community.rstudio.com/tag/tidyclust >> and click the bell icon on the right) to be alerted to any discussions. 

Sorry, I am not sure where the package down site repo is to make a suggestion there, but otherwise I would!

**Comment by EmilHvitfeldt** [comment]
Hello @EconomiCurtis 👋 

That sentence is boilerplate we put in all the tidymodels packages. While I can see the use in having package specific tags, I don't want to modify this sentence, as I would feel the need to modify them in all our packages.

As a team, we are actively monitoring all modeling community questions, so I will see the posts regardless.

Thanks again!
