### ISSUE TITLE
Feature request: more engine arguments

### ISSUE THREAD

**Issue by trevorcampbell** [tidymodels/tidyclust#128]
Hi there!

Thanks for creating this very nice interface to clustering in tidymodels.

Q: Would it be possible to expose more common clustering method arguments in the `k_means` model specification? Thinking specifically about K-means, it would be good to modify the number of random restarts, as well as maybe the max number of iterations (especially since the default engine is "stats", which does not do any fancy kmeans++ initialization as far as I know).

If there's an easy workaround to modify these arguments with the current interface that I'm missing, let me know...

Thanks!

[EDIT]: there is a workaround, but it isn't pretty...
- use `mc_cv` to generate multiple identical resamples of the original data
- fit the clustering on all of those replicas
- use `collect_metrics(summarize = FALSE)` to get the within-cluster sse for all replicas
- use `group_by ... summarize( min() )` pattern to get the minimum within-cluster sse across replicas

**Comment by hfrick** [comment]
Thanks for the issue @trevorcampbell ! 

Do you mean being able to set an argument like `nstart` to `stats::kmeans()`? If so, you can do that via `set_engine()`:
```
kmeans_spec <- k_means(num_clusters = 3) %>%
  parsnip::set_engine("stats", nstart = 5)
```

More details are also in this article: https://tidyclust.tidymodels.org/articles/k_means.html

**Comment by trevorcampbell** [comment]
Oh, that's precisely what I need! How did I miss that in the original article...

Either way, thanks for the help. :-)

**Comment by hfrick** [comment]
Great, glad that's solved!
