### ISSUE TITLE
Documentation for increasing number of iterations for k_means()?

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/tidyclust#133]
Objects created out of `k_means()` seem to have `iter.max` value after inspecting the prepped recipes, but I couldn't find where I can change this value in the documentation. Is it hard coded at 10? I would like to increase it to 30.

**Comment by EmilHvitfeldt** [comment]
The `iter.max` argument that you want to set, can be specified as an engine argument when you use `set_engine()`. This is the same way to access any other arguments not surfaced by `k_means()` itself

``` r
library(tidyclust)

k_means(num_clusters = 2) |>
  set_engine("stats")
#> K Means Cluster Specification (partition)
#> 
#> Main Arguments:
#>   num_clusters = 2
#> 
#> Computational engine: stats

k_means(num_clusters = 2) |>
  set_engine("stats", iter.max = 30)
#> K Means Cluster Specification (partition)
#> 
#> Main Arguments:
#>   num_clusters = 2
#> 
#> Engine-Specific Arguments:
#>   iter.max = 30
#> 
#> Computational engine: stats
```
