### ISSUE TITLE
Engine: kmeans()

### ISSUE THREAD

**Issue by kbodwin** [tidymodels/tidyclust#2]
Discussion thread for the `k_means()` celery function driven by the `kmeans()` engine.

Tuning parameters:

- Number of clusters (`k`)
- Distance metric used (Euclidean, correlation distance, manhattan, etc.)
- Means vs Medians (possibly a separate model spec?)

**Comment by EmilHvitfeldt** [comment]
I'm gonna close this as we have `k_means()` as a model type
