### ISSUE TITLE
Engine: hclust()

### ISSUE THREAD

**Issue by kbodwin** [tidymodels/tidyclust#4]
Discussion thread for implementation of hierarchical/agglomerative clustering `celery` function driven by `hclust()`.

Tuning parameters:

- Linkage: single, complete, average, etc.
- Distance metric

Other considerations:

- Perhaps `fastcluster()` as an alternate engine.
- Agglomerative clustering returns a dendrogram.  Do we want to retain that dendrogram info, i.e. the linkage order, or do we want a fitted model to consist only of cluster assignments?  For the latter, `cuttree()` is the sister function.
- If down the line we're thinking about autoplots - something that doesn't really exist in `tidymodels` right now - `hclust()` comes with a `plot()` method.

**Comment by EmilHvitfeldt** [comment]
I'm gonna close this as we have [hier_clust()](https://tidyclust.tidymodels.org/reference/hier_clust.html)` as a model type
