### ISSUE TITLE
[New Engine]: Add support for mix type clustering algoritm (clustMixType).

### ISSUE THREAD

**Issue by coforfe** [tidymodels/tidyclust#63]
Hi Emil,

It would be very nice to have also the possibility to calculate clusters within a dataset with mixed variable-type of data.
There are some possibilities:

- To integrate `clustMixType` [package](https://cloud.r-project.org/web/packages/clustMixType/index.html).
- or to integrate `kmodes()` function from `klaR` [package](https://cloud.r-project.org/web/packages/klaR/index.html).

Thank again,
Carlos.

**Comment by EmilHvitfeldt** [comment]
Hello @coforfe 👋 

Thanks for the interest! We will take this under advisement
