### ISSUE TITLE
feature suggestion: tune over a grid of different subsets of original variables

### ISSUE THREAD

**Issue by tomazweiss** [tidymodels/tidyclust#78]
Not sure whether this is currently possible with recipes. When doing clustering, I often experiment with using different subsets of variables present in the data. It would be great if such user defined subsets could be specified in a grid and used with `tune()`.

**Comment by EmilHvitfeldt** [comment]
You should be able to do something like this with a workflowsets. We have a PR open here that adds support for {tidyclust} https://github.com/tidymodels/workflowsets/pull/125.
