### ISSUE TITLE
tidyclust model doesn't seem to include dataset labels (as hclust() does)

### ISSUE THREAD

**Issue by bryanosborne** [tidymodels/tidyclust#93]
The R plot() function will use observation labels when plotting dendrograms when passed a model object created by hclust(), but when plot() is passed the model_object$fit it plots the observation row number.
Code that demonstrates this:

############# Hierarchical Clustering ################
library(tidyverse)      # For tidy tools
library(tidyclust)

# Load dataset for analysis
data("USArrests")
df_arrest <- USArrests

# Scale the data
mx_arrest_scaled <- scale(df_arrest, center = TRUE, scale = TRUE)
df_arrest_scaled <- as_tibble(mx_arrest_scaled, rownames = NA)

# Create the specification
hc_arrest_spec <- hier_clust(mode = "partition", engine = "stats",
                      num_clusters = NULL, cut_height = NULL,
                      linkage_method = "complete")

hc_arrest_fit <- hc_arrest_spec %>%
  fit(~., data = df_arrest_scaled)

plot(hc_arrest_fit$fit)

dist_arrest_scaled <- dist(df_arrest_scaled, method="euclidean")

hc <- hclust(dist_arrest_scaled, method = "complete")

plot(hc)

**Comment by EmilHvitfeldt** [comment]
This is happening because the plotting method for the hclust output `?stats:::plot.hclust` uses rownames by default. Since tidyclust uses tibbles internally, this is likely to be lost along the way. You can pass the the original rownames directly to the plotting method

``` r
library(tidyverse)
library(tidyclust)

data("USArrests")
df_arrest <- USArrests

mx_arrest_scaled <- scale(df_arrest, center = TRUE, scale = TRUE)
df_arrest_scaled <- as_tibble(mx_arrest_scaled, rownames = NA)

hc_arrest_spec <- hier_clust(mode = "partition", engine = "stats",
                             num_clusters = NULL, cut_height = NULL,
                             linkage_method = "complete")

hc_arrest_fit <- hc_arrest_spec %>%
  fit(~., data = df_arrest_scaled)

plot(hc_arrest_fit$fit, labels = rownames(df_arrest))
```

![](https://i.imgur.com/AoElCBm.png)

<sup>Created on 2022-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
